### ISSUE TITLE
Lerna badge is outdated

### ISSUE THREAD

**Issue by apalmieri** [telerik/kendo-react-kb#9]
I noticed the link on the badge on the **[README.md](https://github.com/telerik/kendo-react-kb/blob/master/README.md)** that should go to Lerna, still uses **https://lernajs.io/** and the new URL is **[https://lerna.js.org/](https://lerna.js.org/)**

![image](https://user-images.githubusercontent.com/1546183/102851603-4b51ea80-43ea-11eb-87fa-7e7431138856.png)

**Comment by simonssspirit** [comment]
thank you the badge is removed as this repo does not use lerna. Only our main repo
